[package]
name = "hello_graphul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphul = "0.4.5"
tokio = { version = "1.23.0", features = ["full"] }